import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

if (!process.env.GEMINI_API_KEY) {
  console.error("Missing GEMINI_API_KEY in server/.env");
  process.exit(1);
}

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

app.get("/", (req, res) => {
  res.json({ message: "AI Chat backend is running" });
});

app.post("/api/chat", async (req, res) => {
  try {
    const { message, history = [] } = req.body;

    if (!message || !message.trim()) {
      return res.status(400).json({
        error: "Message is required",
      });
    }

    const formattedHistory = history
      .map((msg) => {
        const speaker = msg.role === "user" ? "User" : "Assistant";
        return `${speaker}: ${msg.text}`;
      })
      .join("\n");

    const prompt = `
You are a helpful AI assistant in a chat application.
Respond clearly, naturally, and helpfully.
Use markdown when useful.

Conversation so far:
${formattedHistory}

User: ${message}
Assistant:
    `.trim();

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });

    const reply =
      response?.text?.trim() || "No response generated by Gemini.";

    return res.json({ reply });
  } catch (error) {
    console.error("Gemini API error:", error);

    return res.status(500).json({
      error: "Failed to generate response from Gemini",
      reply: "Sorry, something went wrong while talking to Gemini.",
    });
  }
});

app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});